spring:
  datasource:
    url: jdbc:mysql://localhost:3307/living_bill?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
#mybatis:
#  checkConfigLocation: classpath:db/mybatis/config.xml
#  mybatis.config-location=classpath:db/mybatis/config.xml
mybatis:
  config-location: classpath:db/mybatis/config.xml
