CREATE TABLE USER_ATTACHMENT_TABLE
(
ID                            BIGINT PRIMARY KEY AUTO_INCREMENT,
USER_ID                       BIGINT,
USER_FIRST_CREATED_BILL_TIME  DATE
)DEFAULT CHARSET=utf8mb4;
INSERT INTO USER_ATTACHMENT_TABLE(USER_ID, USER_FIRST_CREATED_BILL_TIME)
VALUES (1,'2020-10-1');
INSERT INTO USER_ATTACHMENT_TABLE(USER_ID, USER_FIRST_CREATED_BILL_TIME)
VALUES (2,'2000-9-1');
INSERT INTO USER_ATTACHMENT_TABLE(USER_ID, USER_FIRST_CREATED_BILL_TIME)
VALUES (3,'2000-8-1');